baseURL = 'http://tumuchdata.org/'
languageCode = 'en-us'
title = 'TUMuchData'
theme = 'nightfall'

[params]
dateFormat = "02.01.2006"
site_logo="images/logo_white.svg"
hostname = "tumuchdata.club"
user = "db"
title = "TUMuchData"
subtitle = "The Munich Database Club"
showMetadata = false
snowflakes = false

[[params.social]]
key = 0
name = "github"
icon="fa-brands fa-github"
url = "https://github.com/tumuchdata"

[[params.social]]
key = 2
name = "linkedin"
icon="fa-brands fa-linkedin-in"
url = "https://www.linkedin.com/company/tumuchdata/"

[[params.social]]
key = 3
name = "email"
icon="fa-solid fa-envelope"
url = "mailto:contact@tumuchdata.club"

[[params.supporters]]
key = 0
name = "QuantCo"
url = "https://www.quantco.com/"
logo = "images/supporters/quantco_Logo.svg"

[[params.supporters]]
key = 1
name = "CedarDB"
url = "https://cedardb.com/"
logo = "images/supporters/CedarDB_Logo.svg"

[[params.supporters]]
key = 2
name = "Firebolt"
url = "https://www.firebolt.io/"
logo = "images/supporters/Firebolt_Logo.svg"

[[params.supporters]]
key = 3
name = "TigerBeetle"
logo = "images/supporters/Tigerbeetle_Logo.svg"

[markup.goldmark.renderer]
unsafe = true # Allow HTML in md files

[taxonomies]
author = "authors"
tag = "tags"
level = "levels"

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1
